runtime: python39
entrypoint: gunicorn -b :$PORT trading_bot_webapp:app

instance_class: F1

automatic_scaling:
  min_instances: 1
  max_instances: 1

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto
